### ISSUE TITLE
ArchLinux/i3 - not working

### ISSUE THREAD

**Issue by JohnAntoine** [Fmstrat/glassit-linux#2]
the extension is not working, i made sure that dependencies are met, willing to do testing/debugging/troubleshooting

distro: Arch
WM: i3
compositor: picom
using the open source vscode variant available in official arch repos (https://www.archlinux.org/packages/?name=code)

EDIT: removed the open source one and installed the Microsoft one, now it works, but all it does is adjust the whole frame transparency, so the text, side bar and everything gets transparency applied to it, just like applying transparency through my compositor.

**Comment by oxodao** [comment]
It doesn't work for me using the official VSCode from Microsoft (visual-studio-code-bin)

**Comment by b1-88er** [comment]
@oxodao `(visual-studio-code-bin)` is a AUR non-official M$ repo.
`pacman -S code`

**Comment by oxodao** [comment]
huh weird. thanks
